# Site settings
title: CodeFrog Hub
email: hub@codefrog.de
description: >
  Top News der CodeFrog Entwickler. 
baseurl: ""
url: "https://codefroghub.github.io"
twitter_username:
github_username:

# Build settings
markdown: kramdown

paginate: 5
paginate_path: "/archiv/:num"