# Site settings
title: CodeFrog Hub
email: hub@codefrog.de
description: >
Top News der CodeFrog Entwickler. 
baseurl: ""
url: "https://codefroghub.github.com"
twitter_username:
github_username:

# Build settings
markdown: kramdown
